apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: troubadour-data
  namespace: troubadour
  labels:
    app: troubadour
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
