#!/bin/sh

# this is just so that I don't have to home-manager switch
# when working on these configs
rm -rf ~/.mozilla/firefox/profiles.ini
rm -rf ~/.local/share/applications/mimeapps.list
rm -rf ~/.gtkrc-2.0
rm -rf ~/.config/mimeapps.list
rm -rf ~/.config/gtk-4.0/settings.ini
rm -rf ~/.config/gtk-4.0/gtk.css
rm -rf ~/.config/gtk-3.0/settings.ini
rm -rf ~/.config/gtk-3.0/gtk.css