#!/bin/sh
# basic but useful
rm -rf ~/.mozilla/firefox/profiles.ini
rm -rf ~/.local/share/applications/mimeapps.list
rm -rf ~/.gtkrc-2.0
rm -rf ~/.config/mimeapps.list
rm -rf ~/.config/gtk-4.0/settings.ini
rm -rf ~/.config/gtk-4.0/gtk.css
rm -rf ~/.config/gtk-3.0/settings.ini
rm -rf ~/.config/gtk-3.0/gtk.css

