#!/bin/bash

# Startup folder cloning and installation from github

projectList = ["termify","discord-bot","linux_manager","hockey-pool"]
configList = ["kitty-configs","i3-configs","neovim-configs","vscode-configs"]

# Create folder
mkdir ~/work
mkdir ~/projects
mkdir ~/configs

# Cloning project repos from list

for project in projectList; do;
    cd ~/work/projects
    git clone git@github.com:grosheth/${project}.git ${project}
done

# Cloning config repos from list

for config in configList; do;
    cd ~/work/configs
    git clone git@github.com:grosheth/${config}.git ${config}
done
